---
- hosts: server
  tasks:
  - name: download nexus url
    get_url:
      url: https://download.sonatype.com/nexus/3/nexus-3.30.1-01-unix.tar.gz
      dest: /opt
      mode: 0777
  - name: extract file
    unarchive:
      src: /opt/nexus-3.30.1-01-unix.tar.gz
      dest: /opt
      remote_src: True
  - name: Create nexus user and Group
    user:
      name: nexus
      state: present
  - name: Change directory nexus permissions
    file:
      path: /opt/nexus-3.30.1-01
      state: directory
      recurse: yes
      owner: nexus
      group: nexus
      mode: '0755'
  - name: Change directory sonatype-work permissions
    file:
      path: /opt/sonatype-work
      state: directory
      recurse: yes
      owner: nexus
      group: nexus
      mode: '0755'
  - name: nexus service file template
    template:
      src: nexus.service
      dest: /opt/nexus.service
  - name: Copy nexus service from local to remote
    copy:
      src: /opt/nexus.service
      dest: /etc/systemd/system/
      mode: 0777
      remote_src: yes
  - name: just force systemd to reread configs (2.4 and above)
    systemd:
      daemon_reload: yes
  - name: enable nexus startup
    service:
      name: nexus
      state: restarted
